// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA85f2siF2-7OhNrV7vZsckJzpA-STZN6o',
    appId: '1:1099424508278:web:993dade85a66a7bfe33257',
    messagingSenderId: '1099424508278',
    projectId: 'rarvi-dcb61',
    authDomain: 'rarvi-dcb61.firebaseapp.com',
    storageBucket: 'rarvi-dcb61.firebasestorage.app',
    measurementId: 'G-3ZK0HC0SDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCYKCqOxpqGQbK8eelmfuSJM2qMGQa3k',
    appId: '1:1099424508278:android:3cff81bd41c332bce33257',
    messagingSenderId: '1099424508278',
    projectId: 'rarvi-dcb61',
    storageBucket: 'rarvi-dcb61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOSEXMkOUcPyUeL0P_v2ckbEQIXHnGio',
    appId: '1:1099424508278:ios:0f314e7355dbc6abe33257',
    messagingSenderId: '1099424508278',
    projectId: 'rarvi-dcb61',
    storageBucket: 'rarvi-dcb61.firebasestorage.app',
    iosBundleId: 'com.example.rarvi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOSEXMkOUcPyUeL0P_v2ckbEQIXHnGio',
    appId: '1:1099424508278:ios:0f314e7355dbc6abe33257',
    messagingSenderId: '1099424508278',
    projectId: 'rarvi-dcb61',
    storageBucket: 'rarvi-dcb61.firebasestorage.app',
    iosBundleId: 'com.example.rarvi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA85f2siF2-7OhNrV7vZsckJzpA-STZN6o',
    appId: '1:1099424508278:web:3a10d604a1fb6dbbe33257',
    messagingSenderId: '1099424508278',
    projectId: 'rarvi-dcb61',
    authDomain: 'rarvi-dcb61.firebaseapp.com',
    storageBucket: 'rarvi-dcb61.firebasestorage.app',
    measurementId: 'G-8YJM1RKJYX',
  );

}