name: Build and Commit APK

on:
  push:
    branch:
      - '*'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        run: flutter build apk --release

      - name: Copy APK to tracked path
        run: |
          mkdir -p release-apks
          cp build/app/outputs/flutter-apk/app-release.apk release-apks/app-release.apk

      - name: Commit APK
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add release-apks/app-release.apk
          git commit -m "Build APK on CI"
          git push
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
